### ISSUE TITLE
SRORAM gives random numbers, recursive binary ORAM and recursive TP ORAM give run-time error messages

### ISSUE THREAD

**Issue by kholoudAlSaleh** [InitialDLab/SEAL-ORAM#1]
I faced the following issues when running the test-bed:  
1)  SRORM:  the run gives random numbers unlike the other ORAMs where the numbers are listed from 0... 1023. 

2) Recursive Binary ORAM: gives the following run-time error message:
 terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 4) > this->size() (which is 0)
Aborted (core dumped)

3) Recursive TP ORAM:  gives the following run-time error message:
Segmentation fault (core dumped)

Pleases note:  The parameters that I used in the config.h are the same as the ones used in the SEAL ORAM test-bed, I didn't change any of them. I am using windows 10 and I have installed the Oracle virtual machine to install Ubuntu 16.04. I have used the MongoDB legacy driver and every thing you listed in the GitHub page.

Thank you and regards,
Kholoud

**Comment by dongx-psu** [comment]
There is something I haven't listed on the README (which I probably should). First, you need to make sure you compile the mongo legacy driver with C++11 enabled. Generally, you want a build script like this:

    scons --prefix=/usr/local --c++11=on --disable-warnings-as-errors install

I think at least this will make the SRORAM running. It is weird that the program will get errors when the c++11 flag is not on. So do make sure the flag is there when you compile the mongo legacy driver.

There are also some errors that can happen at the end of recursive ORAMs during the deconstruction in my experience. I will try to get some time looking into your issues.

**Comment by kholoudAlSaleh** [comment]
I have solved the problem it has to do with the size of the memory. When I ran it on a server with 128 G RAM it worked.

Thank you and regards,
Kholoud
